version: '2'
services:
  lrs:
      image: dirichlet/lrs
      ports:
          - "8080:8080"
      links:
          - postgres
          - rabbitmq
      env_file:
          - lrs.env
          - psql.env
          - rabbitmq.env

  postgres:
      image: postgres
      env_file: psql.env
      volumes:
          - psql_data:/var/lib/postgresql/data/pgdata

  rabbitmq:
      image: rabbitmq:3.6
      env_file: rabbitmq.env
      privileged: true

volumes:
  psql_data:
    driver: local
